### ISSUE TITLE
Nun va

### ISSUE THREAD

**Issue by dadadani** [giovanniacanforah/bottino#1]
Nun va u cazzu

**Comment by TyroneFromJail** [comment]
@dadadani si

**Comment by dadadani** [comment]
Ma la surcio mettere in vps e fare php start bottino.php dare messaggio usare managerfatherbot rusolvere

**Comment by giovanniacanforah** [comment]
@dadadani 🥴

**Comment by dadadani** [comment]
🎷

**Comment by giovanniacanforah** [comment]
Fai php bottino.php install

**Comment by dadadani** [comment]
Avere messo versione - buggata vedere

**Comment by giovanniacanforah** [comment]
ho visto, grazie del supporto!

**Comment by XYN0N** [comment]
Wow, il code funziona! Grazie Giovanni.
//Il code non funziona, fuck! 
xD

**Comment by giovanniacanforah** [comment]
prego. questa è ultima tecnologia
### ffff ### fff

> [``](url)

**Comment by XYN0N** [comment]
U-U

**Comment by giovanniacanforah** [comment]
basta chiudo sto coso cia

**Comment by XYN0N** [comment]
Ok sir

**Comment by giovanniacanforah** [comment]
ma se si chiude fa comunque scrivere

**Comment by XYN0N** [comment]
hahaha git bugged
